/**
 * Cross-implementation parity tests for the extension-backup keystore reader.
 *
 * The fixture below was generated AND decrypt-verified by the browser
 * extension's own src/crypto/keystoreCrypto.ts (hash-wasm argon2id +
 * WebCrypto AES-256-GCM), so a passing decrypt here proves byte-level
 * compatibility with real extension exports. Do not regenerate casually:
 * the point of pinning it is that this repo's implementation must follow
 * the extension's bytes, not its own.
 */
import {
  looksLikeKeystoreBackup,
  parseKeystoreBackup,
  decryptKeystoreToHexSeed,
  KeystoreFormatError,
  KeystoreDecryptError,
  type EncryptedKeystore,
} from '../keystoreBackup';
import { deriveArgon2id, _setWasmUnavailableForTests } from '../argon2';

const SEED_HEX =
  '0x010000cea755979937e2dc6137c0e51ba0d1eb2a44920cefffb1a860cf194ea7d23d694045fd2c8a72ec5aecf1e7e5bb591ff2';
const ASCII_PASSWORD = 'correct horse battery staple';
const UNICODE_PASSWORD = 'pässwörd-café-\u{1f511}';

// Generated by the extension's encryptKeystore (m=8192/t=2 for test speed;
// production exports use m=262144/t=8, same code path).
const EXTENSION_ENVELOPE = {
  version: '0.1.1',
  exportedAt: '2026-07-28T00:00:00.000Z',
  keystores: [
    {
      version: 1,
      id: '1e198746-9ccd-4815-b1bc-dabe655a3271',
      address: 'Qcfec0cbee560cbd6ed89580204af71448f1fb8c5',
      crypto: {
        ciphertext:
          '8a4d7e503009e1ea9161d1a95472f1b5aa1e217a2c499869d9b9b3cf0ea77e2710cfc30c313917532111a66ceae0f4b6580ddae333664bcc687c2e1feb73874f220c19',
        cipherparams: { iv: '4e0b9d062b34e456c3996646' },
        cipher: 'aes-256-gcm',
        kdf: 'argon2id',
        kdfparams: {
          m: 8192,
          t: 2,
          p: 1,
          dklen: 32,
          salt: '6f02765040f3e6b2fdee34a2c06ecbc9cd31debb52ba75b620023dc7a6b1b7e4',
        },
      },
    },
    {
      version: 1,
      id: '8cba780e-93e8-48aa-ab70-e58b0745aa29',
      address: 'Qcfec0cbee560cbd6ed89580204af71448f1fb8c5',
      crypto: {
        ciphertext:
          'e68ae39592aad9b71381ab3c19730f31d2e703a79efdb5570034dd2182656e654bca16725144d13b2b27f6396d348f1a7213897b14949ef27631acf677b1c102226eef',
        cipherparams: { iv: 'd3702f8aec68875517976829' },
        cipher: 'aes-256-gcm',
        kdf: 'argon2id',
        kdfparams: {
          m: 8192,
          t: 2,
          p: 1,
          dklen: 32,
          salt: '4f935e4a7c736e02fbba331f90bdd0c72e27bc019f91adfef7ed56a467c71a8d',
        },
      },
    },
  ],
  accounts: [
    'Qcfec0cbee560cbd6ed89580204af71448f1fb8c5',
    'Qcfec0cbee560cbd6ed89580204af71448f1fb8c5',
  ],
  activeChain: { chainId: '0x539', chainName: 'QRL Zond Testnet v2' },
};

function keystoreAt(index: number): EncryptedKeystore {
  const ks = parseKeystoreBackup(EXTENSION_ENVELOPE)[index];
  if (!ks) throw new Error(`fixture missing keystore #${index}`);
  return ks;
}
const firstKeystore = (): EncryptedKeystore => keystoreAt(0);

function withKdfParam(overrides: Record<string, number>): EncryptedKeystore {
  const ks = firstKeystore();
  return {
    ...ks,
    crypto: {
      ...ks.crypto,
      kdfparams: { ...ks.crypto.kdfparams, ...overrides },
    },
  };
}

describe('looksLikeKeystoreBackup', () => {
  it('recognizes the extension envelope', () => {
    expect(looksLikeKeystoreBackup(EXTENSION_ENVELOPE)).toBe(true);
  });

  it('recognizes a single bare keystore', () => {
    expect(looksLikeKeystoreBackup(EXTENSION_ENVELOPE.keystores[0])).toBe(true);
  });

  it('rejects the web wallet v2 file shape', () => {
    expect(
      looksLikeKeystoreBackup({
        address: 'Q1',
        encryptedData: 'aa',
        salt: 'bb',
        iv: 'cc',
        version: 'v2',
        timestamp: 1,
      }),
    ).toBe(false);
  });

  it('rejects non-objects', () => {
    expect(looksLikeKeystoreBackup(null)).toBe(false);
    expect(looksLikeKeystoreBackup('json')).toBe(false);
  });
});

describe('parseKeystoreBackup', () => {
  it('parses both keystores from the envelope', () => {
    const keystores = parseKeystoreBackup(EXTENSION_ENVELOPE);
    expect(keystores).toHaveLength(2);
    expect(keystores[0]?.address).toBe('Qcfec0cbee560cbd6ed89580204af71448f1fb8c5');
  });

  it('accepts a single bare keystore object', () => {
    const keystores = parseKeystoreBackup(EXTENSION_ENVELOPE.keystores[0]);
    expect(keystores).toHaveLength(1);
  });

  it('rejects an empty keystores array', () => {
    expect(() => parseKeystoreBackup({ keystores: [] })).toThrow(KeystoreFormatError);
  });

  it.each([
    ['version', { ...firstKeystore(), version: 2 }],
    ['cipher', { ...firstKeystore(), crypto: { ...firstKeystore().crypto, cipher: 'aes-256-cbc' } }],
    ['kdf', { ...firstKeystore(), crypto: { ...firstKeystore().crypto, kdf: 'scrypt' } }],
  ])('rejects unsupported %s', (_label, keystore) => {
    expect(() => parseKeystoreBackup({ keystores: [keystore] })).toThrow(KeystoreFormatError);
  });

  it.each([
    ['m below bounds', { m: 4095 }],
    ['m above bounds', { m: 1048577 }],
    ['t below bounds', { t: 1 }],
    ['t above bounds', { t: 51 }],
    ['p above bounds', { p: 17 }],
    ['dklen below bounds', { dklen: 15 }],
    ['non-integer m', { m: 8192.5 }],
  ])('rejects kdfparams with %s', (_label, overrides) => {
    expect(() => parseKeystoreBackup({ keystores: [withKdfParam(overrides)] })).toThrow(
      KeystoreFormatError,
    );
  });

  it('rejects in-bounds dklen other than 32 at decrypt time as a format error', async () => {
    // dklen 64 passes the parity bounds but AES-256 needs exactly 32 bytes;
    // this must not be misreported as a wrong password.
    await expect(
      decryptKeystoreToHexSeed(withKdfParam({ dklen: 64 }), ASCII_PASSWORD),
    ).rejects.toThrow(KeystoreFormatError);
  });

  it('rejects a wrong-length IV', () => {
    const ks = firstKeystore();
    ks.crypto.cipherparams.iv = 'aabbcc';
    expect(() => parseKeystoreBackup({ keystores: [ks] })).toThrow(KeystoreFormatError);
  });

  it('rejects non-hex ciphertext', () => {
    const ks = firstKeystore();
    ks.crypto.ciphertext = 'zz' + ks.crypto.ciphertext.slice(2);
    expect(() => parseKeystoreBackup({ keystores: [ks] })).toThrow(KeystoreFormatError);
  });

  it('rejects a ciphertext that is not exactly seed+tag sized', () => {
    // 51-byte seed + 16-byte GCM tag = 67 bytes; wrong-era or corrupt files
    // must fail at parse, not after a correct password. Extension parity.
    for (const bytes of [66, 68, 80]) {
      const ks = firstKeystore();
      ks.crypto.ciphertext = '00'.repeat(bytes);
      expect(() => parseKeystoreBackup({ keystores: [ks] })).toThrow(KeystoreFormatError);
    }
  });

  it("rejects a salt below argon2's 8-byte minimum", () => {
    const ks = firstKeystore();
    ks.crypto.kdfparams.salt = 'abcd';
    expect(() => parseKeystoreBackup({ keystores: [ks] })).toThrow(KeystoreFormatError);
  });
});

describe('decryptKeystoreToHexSeed (extension parity)', () => {
  it('decrypts an extension-encrypted keystore (ASCII password)', async () => {
    await expect(decryptKeystoreToHexSeed(keystoreAt(0), ASCII_PASSWORD)).resolves.toBe(
      SEED_HEX,
    );
  });

  it('decrypts an extension-encrypted keystore (Unicode password)', async () => {
    await expect(decryptKeystoreToHexSeed(keystoreAt(1), UNICODE_PASSWORD)).resolves.toBe(
      SEED_HEX,
    );
  });

  it('decrypts with an NFD-normalized variant of the same password', async () => {
    // The extension NFC-normalizes before the KDF; a visually identical
    // password typed on a platform that produces NFD must still work.
    await expect(
      decryptKeystoreToHexSeed(keystoreAt(1), UNICODE_PASSWORD.normalize('NFD')),
    ).resolves.toBe(SEED_HEX);
  });

  it('rejects a wrong password with KeystoreDecryptError', async () => {
    await expect(decryptKeystoreToHexSeed(keystoreAt(0), 'wrong-password')).rejects.toThrow(
      KeystoreDecryptError,
    );
  });

  it('rejects an empty password', async () => {
    await expect(decryptKeystoreToHexSeed(keystoreAt(0), '')).rejects.toThrow(
      KeystoreDecryptError,
    );
  });

  it('rejects tampered ciphertext', async () => {
    const ks = firstKeystore();
    const flipped = (parseInt(ks.crypto.ciphertext.slice(0, 2), 16) ^ 0x01)
      .toString(16)
      .padStart(2, '0');
    ks.crypto.ciphertext = flipped + ks.crypto.ciphertext.slice(2);
    await expect(decryptKeystoreToHexSeed(ks, ASCII_PASSWORD)).rejects.toThrow(
      KeystoreDecryptError,
    );
  });
});

describe('argon2id implementations agree', () => {
  // Explicit timeouts: the pure-JS derivation takes 4-6s even at the fast
  // test params and flakes against jest's 5s default on loaded runners.
  it('hash-wasm and @noble/hashes derive identical keys', async () => {
    const password = new TextEncoder().encode(UNICODE_PASSWORD.normalize('NFC'));
    const salt = new Uint8Array(32).fill(7);
    const params = { m: 8192, t: 2, p: 1, dklen: 32 };

    _setWasmUnavailableForTests(false);
    const viaWasm = await deriveArgon2id(password, salt, params);
    _setWasmUnavailableForTests(true);
    const viaJs = await deriveArgon2id(password, salt, params);
    _setWasmUnavailableForTests(false);

    expect(Buffer.from(viaWasm).toString('hex')).toBe(Buffer.from(viaJs).toString('hex'));
  }, 30000);

  it('the pure-JS fallback decrypts the extension fixture too', async () => {
    _setWasmUnavailableForTests(true);
    try {
      await expect(decryptKeystoreToHexSeed(keystoreAt(0), ASCII_PASSWORD)).resolves.toBe(
        SEED_HEX,
      );
    } finally {
      _setWasmUnavailableForTests(false);
    }
  }, 30000);
});
